controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

root:
    path: /
    controller: App\Controller\SecurityController::login
    
admin_route:
    path: /admin
    controller: App\Controller\AdminController::index

user_route:
    path: /user
    controller: App\Controller\UserController::index

